sudo: required

language: node_js

node_js:
  - "10"

before_install:
  - yarn

script:
  - chmod a+x deploy-doc.sh && sh deploy-doc.sh

branches:
  only:
  - master

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email:
    recipients:
      - travis-ci@henry.wang
