version: "3"
services:
  database.postgres:
    image: sameersbn/postgresql:latest
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - PG_PASSWORD=ttrss # please change the password
      - DB_EXTENSION=pg_trgm
    # volumes:
    #   - ~/postgres/data/:/var/lib/postgresql/ # persist postgres data to ~/postgres/data/ on the host
    restart: always

  service.rss:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ttrss
    ports:
      - 181:80
    environment:
      - SELF_URL_PATH=http://ttrss.serveo.net/ # please change to your own domain
      - DB_HOST=database.postgres
      - DB_PORT=5432
      - DB_NAME=ttrss
      - DB_USER=postgres
      - DB_PASS=ttrss # please change the password
      - ENABLE_PLUGINS=auth_internal,fever # auth_internal is required. Plugins enabled here will be enabled for all users as system plugins
    stdin_open: true
    tty: true
    restart: always
    command: sh -c 'sh /wait-for.sh database.postgres:5432 -- php /configure-db.php && exec s6-svscan /etc/s6/'

# ssh -R ttrss:80:localhost:181 serveo.net
